on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Levantar base de datos
        run: make postgres
        env:
          # Rellenamos las variables de entorno secretas
          # con unas de repuesto
          DB_USER: user
          DB_PASSWORD: password
          DB_NAME: laser_chess_db
          DB_PORT: 5432

      - name: Instalar golang
        uses: actions/setup-go@v6
        with: 
          go-version: '1.25.x'
    
      - name: Instalar sqlc
        uses: sqlc-dev/setup-sqlc@v3
        with:
          sqlc-version: '1.30.0'

      - name: Esperar a que postgresql termine de levantarse
        run: sleep 10
         
      - name: Aplicar esquema de base de datos
        run: make apply schema

      - name: Hacer la build
        run: make build
        env:
          DB_USER: user
          DB_PASSWORD: password
          DB_NAME: laser_chess_db
          DB_PORT: 5432
          DB_URL: "postgresql://user:password@localhost:5432/laser_chess_db?sslmode=disable"
          # Hacer que se ejecute en modo release
          GIN_MODE: release
          
      
