on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Levantar base de datos
        run: docker compose up -d
        env:
          # Rellenamos las variables de entorno secretas
          # con unas de repuesto
          DB_USER: user
          DB_PASSWORD: password
          DB_NAME: laser_chess_db
          DB_PORT: 5432

      - name: Instalar golang
        uses: actions/setup-go@v6
        with: 
          go-version: '1.25.x'
    
      - name: Instalar dependencias
        run: |
          # Hacer go install es muy lento, descargamos el binario desde las releases de github directamente
          curl -L https://github.com/sqlc-dev/sqlc/releases/download/v1.30.0/sqlc_1.30.0_linux_amd64.tar.gz | tar xvz
          sudo mv sqlc /usr/local/bin/

          curl -L https://github.com/golang-migrate/migrate/releases/download/v4.18.2/migrate.linux-amd64.tar.gz | tar xvz
          sudo mv migrate /usr/local/bin/

      - name: Esperar a que postgresql termine de levantarse
        run: sleep 10
         
      - name: Hacer la build
        run: make build
        env:
          DB_USER: user
          DB_PASSWORD: password
          DB_NAME: laser_chess_db
          DB_PORT: 5432
          DB_URL: "postgresql://user:password@localhost:5432/laser_chess_db?sslmode=disable"
          # Hacer que se ejecute en modo release
          GIN_MODE: release
          
      
